/**
 * @externs
 * @suppress {duplicate}
 */
// NOTE: generated by tsickle, do not edit.
// externs from types.d.ts:
 /** @type {?} */
var webkitAudioContext;
 /** @type {?} */
var requestIdleCallback;

/** @record @struct */
function WhatWGEventListenerArgs() {}
 /** @type {?} */
WhatWGEventListenerArgs.prototype.capture;

/** @record @struct */
function WhatWGAddEventListenerArgs() {}
 /** @type {?} */
WhatWGAddEventListenerArgs.prototype.passive;
 /** @type {?} */
WhatWGAddEventListenerArgs.prototype.once;

/** @typedef {?} */
var WhatWGAddEventListener;
