var f="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(){k=function(){};h.Symbol||(h.Symbol=aa)}var ba=0;function aa(a){return"jscomp_symbol_"+(a||"")+ba++}
function l(){k();var a=h.Symbol.iterator;a||(a=h.Symbol.iterator=h.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&f(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return m(this)}});l=function(){}}function m(a){var b=0;return ca(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ca(a){l();a={next:a};a[h.Symbol.iterator]=function(){return this};return a}function p(a){l();k();l();var b=a[Symbol.iterator];return b?b.call(a):m(a)}
for(var r=h,t=["Promise"],u=0;u<t.length-1;u++){var v=t[u];v in r||(r[v]={});r=r[v]}
var w=t[t.length-1],x=r[w],y=function(){function a(a){this.b=0;this.i=void 0;this.a=[];var d=this.f();try{a(d.resolve,d.reject)}catch(n){d.reject(n)}}function b(){this.a=null}function c(d){return d instanceof a?d:new a(function(a){a(d)})}if(x)return x;b.prototype.b=function(a){this.a||(this.a=[],this.h());this.a.push(a)};b.prototype.h=function(){var a=this;this.f(function(){a.o()})};var g=h.setTimeout;b.prototype.f=function(a){g(a,0)};b.prototype.o=function(){for(;this.a&&this.a.length;){var a=this.a;
this.a=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(I){this.i(I)}}}this.a=null};b.prototype.i=function(a){this.f(function(){throw a;})};a.prototype.f=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.F),reject:a(this.h)}};a.prototype.F=function(b){if(b===this)this.h(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof a)this.G(b);else{a:switch(typeof b){case "object":var d=null!=b;break a;case "function":d=
!0;break a;default:d=!1}d?this.D(b):this.o(b)}};a.prototype.D=function(a){var b=void 0;try{b=a.then}catch(n){this.h(n);return}"function"==typeof b?this.H(b,a):this.o(a)};a.prototype.h=function(a){this.v(2,a)};a.prototype.o=function(a){this.v(1,a)};a.prototype.v=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.b);this.b=a;this.i=b;this.C()};a.prototype.C=function(){if(this.a){for(var a=this.a,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.a=
null}};var e=new b;a.prototype.G=function(a){var b=this.f();a.m(b.resolve,b.reject)};a.prototype.H=function(a,b){var d=this.f();try{a.call(b,d.resolve,d.reject)}catch(I){d.reject(I)}};a.prototype.then=function(b,c){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(ga){g(ga)}}:b}var e,g,q=new a(function(a,b){e=a;g=b});this.m(d(b,e),d(c,g));return q};a.prototype.catch=function(a){return this.then(void 0,a)};a.prototype.m=function(a,b){function d(){switch(c.b){case 1:a(c.i);break;
case 2:b(c.i);break;default:throw Error("Unexpected state: "+c.b);}}var c=this;this.a?this.a.push(function(){e.b(d)}):e.b(d)};a.resolve=c;a.reject=function(b){return new a(function(a,c){c(b)})};a.race=function(b){return new a(function(a,d){for(var e=p(b),g=e.next();!g.done;g=e.next())c(g.value).m(a,d)})};a.all=function(b){var d=p(b),e=d.next();return e.done?c([]):new a(function(a,b){function g(b){return function(c){q[b]=c;n--;n||a(q)}}var q=[],n=0;do q.push(void 0),n++,c(e.value).m(g(q.length-1),
b),e=d.next();while(!e.done)})};return a}();y!=x&&null!=y&&f(r,w,{configurable:!0,writable:!0,value:y});"serviceWorker"in navigator&&(navigator.serviceWorker.register("./sw.js").then(function(){console.log("service worker is all cool.")}).catch(function(a){console.error("service worker is not so cool.",a);throw a;}),navigator.serviceWorker.controller&&(navigator.serviceWorker.controller.onstatechange=function(a){"redundant"===a.target.state&&document.querySelector("#reload-prompt").classList.remove("hidden")}));
var z="onpointerdown"in document.createElement("div"),A=0,B=new ("undefined"!==typeof webkitAudioContext?webkitAudioContext:AudioContext),C=B.createGain();C.connect(B.destination);
var D={c:!1,B:window.localStorage.getItem("fidget_spinner")||"./assets/spinners/base.png",muted:"true"===window.localStorage.getItem("fidget_muted")?!0:!1,l:window.localStorage.getItem("fidget_spins")?parseInt(window.localStorage.getItem("fidget_spins"),10):0,j:window.localStorage.getItem("fidget_max_velocity")?parseInt(window.localStorage.getItem("fidget_max_velocity"),10):0},da=[{path:"./assets/spinners/base.png",name:"The Classic",g:0},{path:"./assets/spinners/triple.png",name:"The Triple",g:500},
{path:"./assets/spinners/pokeball.png",name:"The 'Chu",g:2E3},{path:"./assets/spinners/cube.png",name:"The Cubist",g:5E3},{path:"./assets/spinners/fractal.png",name:"The Fractal",g:1E4}],ea=document.getElementById("turns"),fa=document.getElementById("velocity"),ha=document.getElementById("maxVelocity"),E=document.getElementById("spinner"),ia=document.getElementById("trace-slow"),ja=document.getElementById("trace-fast"),F=document.getElementById("toggle-audio"),ka=Array.from(document.getElementsByClassName("spinner")),
la=document.getElementById("picker"),G=document.getElementById("spinner-picker"),H=0,J=0;function K(a){"undefined"!==typeof requestIdleCallback?requestIdleCallback(a,{timeout:60}):"undefined"!==typeof requestAnimationFrame?requestAnimationFrame(a):setTimeout(a,16.66)}
function ma(){A=Math.abs(3600*J/2/Math.PI)|0;var a=Math.max(A,D.j);D.j!==a&&(K(function(){return window.localStorage.setItem("fidget_max_velocity",""+D.j)}),D.j=a);D.l+=Math.abs(J/2/Math.PI);K(function(){return window.localStorage.setItem("fidget_spins",""+D.l)});a=D.j.toLocaleString(void 0,{maximumFractionDigits:1});ea.textContent=""+D.l.toLocaleString(void 0,{maximumFractionDigits:0});fa.textContent=""+A;ha.textContent=""+a}
var L=E.getBoundingClientRect(),na=L.left+L.width/2,oa=L.top+L.height/2,M=L.width/10,N=0,O=0,P=!1,Q=0,R=0;function S(a){return{x:("touches"in a?a.touches[0].clientX:a.clientX)-na,y:("touches"in a?a.touches[0].clientY:a.clientY)-oa}}function pa(a){if(!D.c){var b=S(a),c=b.x,b=b.y;T(a);P=!0;O=Math.sqrt(Math.pow(c,2)+Math.pow(b,2));R=N}}function T(a){if(!D.c){var b=S(a);N=Math.atan2(b.x,b.y);a.preventDefault()}}function U(){D.c||(P=!1)}
function V(){requestAnimationFrame(function(){P?O>M&&(Q=N-R,Q<-Math.PI&&(Q+=2*Math.PI),Q>Math.PI&&(Q-=2*Math.PI),J=Q,R=N):Q&&(J=Q*O/M,Q=0);H-=J;E.style.transform="rotate("+H+"rad)";ia.style.opacity=.2<Math.abs(J)?"1":"0.00001";ja.style.opacity=.4<Math.abs(J)?"1":"0.00001";ma();J*=.99;J=Math.sign(J)*Math.max(0,Math.abs(J)-2E-4);var a=Math.abs(A*Math.PI/60);if(a&&!P){var b=a,c=B.currentTime,g=b,b=Math.min(1,b/10);if(!(c+(b*(2-b)*1.1-(.6-.6*b*(2-b)))-b*(2-b)<W)){var e=B.createOscillator(),d=B.createGain(),
b=Math.min(1,Math.max(0,b));e.type="triangle";e.connect(d);d.connect(C);g=qa(g);b=.1*(1-b/2);e.frequency.setValueAtTime(g,c);e.frequency.linearRampToValueAtTime(1.8*g,c+=b);W=c+b;d.gain.setValueAtTime(.1,B.currentTime);d.gain.linearRampToValueAtTime(0,W);e.start(B.currentTime);e.stop(W)}d=a;a=B.currentTime;b=d;d=Math.min(1,d/10);a+(d*(2-d)*1.1-(.3-.3*d*(2-d)))-d*(2-d)<X||(c=B.createOscillator(),e=B.createGain(),d=Math.min(1,Math.max(0,d)),c.type="sine",c.connect(e),e.connect(C),b=ra(b),d=.05*(1-d/
2),c.frequency.setValueAtTime(b,a),c.frequency.linearRampToValueAtTime(1.8*b,a+=d),X=a+d,e.gain.setValueAtTime(.15,B.currentTime),e.gain.linearRampToValueAtTime(0,X),c.start(B.currentTime),c.stop(X))}V()})}var W=-1,X=-1;function Y(a){return function(b){return a.u+(b-a.s)/(a.w-a.s)*(a.A-a.u)}}var qa=Y({s:0,w:80,u:400,A:2E3}),ra=Y({s:0,w:80,u:300,A:1500});
function sa(){function a(){var b=B.createBufferSource();b.buffer=B.createBuffer(1,1,22050);b.connect(B.destination);"undefined"===typeof b.start?b.noteOn(0):b.start(0);b.onended=function(){b.disconnect(0);document.removeEventListener("touchend",a,!0)}}document.addEventListener("touchend",a,!0)}function Z(){F.classList.toggle("muted",D.muted);C.gain.setValueAtTime(D.muted?0:1,B.currentTime);window.localStorage.setItem("fidget_muted",""+D.muted)}
function ta(){!0!==D.c?(D.c=!D.c,history.pushState(D,"","#picker"),ua()):history.back()}function va(a){D.muted=!D.muted;Z();a.stopPropagation()}function wa(a){D.B=a;K(function(){return window.localStorage.setItem("fidget_spinner",a)});for(var b=p(ka),c=b.next();!c.done;c=b.next())c.value.src=a}function xa(a){var b=a.target;"IMG"!==b.tagName||b.classList.contains("locked")||(wa(a.target.src),ta())}
function ua(){for(var a=G.innerHTML="",b=p(da),c=b.next();!c.done;c=b.next())c=c.value,a+='<li><p class="title">'+c.name+"</p>",a=c.g>=D.l?a+('<img width="300" height="300" class="locked" src="'+c.path+'"><p class="locked-info">Unlocks at '+c.g+" spins</p>"):a+('<img width="300" height="300" src="'+c.path+'">'),a+="</li>";G.innerHTML=a;G.classList.remove("hidden");G.scrollTop=0}
(function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(g,e){function d(a){a.done?g(a.value):Promise.resolve(a.value).then(b,c).then(d,e)}d(a.next())})})(function(){function a(){for(;;)switch(b){case 0:Z(),sa(),V(),c=document.addEventListener,la.addEventListener(z?"pointerdown":"touchstart",ta),G.addEventListener("click",xa),F.addEventListener(z?"pointerdown":"touchstart",va),c(z?"pointerdown":"touchstart",pa,{passive:!1}),c(z?"pointermove":"touchmove",
T,{passive:!1}),c(z?"pointerup":"touchend",U),c(z?"pointercancel":"touchcancel",U),history.replaceState(null,"","/"),wa(D.B),window.onpopstate=function(a){null===a.state?(D.c=!1,G.classList.add("hidden")):null!==a.state&&(D.c=!0,ua())},b=-1;default:return{value:void 0,done:!0}}}var b=0,c,g={next:function(){return a()},throw:function(){return a()},return:function(){throw Error("Not yet implemented");}};l();g[Symbol.iterator]=function(){return this};return g}());
